name: PackStacker
version: ${version}
author: tlm920
main: com.timomcgrath.packstacker.PackStacker
api-version: '1.20'
commands:
  pack:
    usage: '/pack'
    description: 'Core command to load and manage resource packs.'
    aliases:
      - resourcepack
      - pck
      - loadpack
permissions:
  pack.load.self:
    description: User is able to run /pack load
    default: true
  pack.load.others:
    description: User is able to run /pack load on other players
    default: false